#!/bin/bash
BIOCENTER_MENU_PAGE="http://www.biocenter.ku.dk/kantine/menuoversigt/"
AUGUSTKROGH_MENU_PAGE="http://www1.bio.ku.dk/akb/kantine/menuoversigt/"

BIOCENTER_MENU=`curl -s $BIOCENTER_MENU_PAGE | grep -h 'tr height=' | html2text`
AUGUSTKROGH_MENU=`curl -s $AUGUSTKROGH_MENU_PAGE | grep -h 'tr height=' | html2text`
echo "BIOCENTER"
echo "$BIOCENTER_MENU"
echo "AUGUST KROGH"
echo "$AUGUSTKROGH_MENU"
